// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: proto/flow.proto

package pbflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// as defined by field 61 in
// https://www.iana.org/assignments/ipfix/ipfix.xhtml
type Direction int32

const (
	Direction_INGRESS Direction = 0
	Direction_EGRESS  Direction = 1
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "INGRESS",
		1: "EGRESS",
	}
	Direction_value = map[string]int32{
		"INGRESS": 0,
		"EGRESS":  1,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_flow_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_proto_flow_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_proto_flow_proto_rawDescGZIP(), []int{0}
}

// intentionally empty
type CollectorReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorReply) Reset() {
	*x = CollectorReply{}
	mi := &file_proto_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorReply) ProtoMessage() {}

func (x *CollectorReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorReply.ProtoReflect.Descriptor instead.
func (*CollectorReply) Descriptor() ([]byte, []int) {
	return file_proto_flow_proto_rawDescGZIP(), []int{0}
}

type Records struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Record              `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Records) Reset() {
	*x = Records{}
	mi := &file_proto_flow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Records) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Records) ProtoMessage() {}

func (x *Records) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Records.ProtoReflect.Descriptor instead.
func (*Records) Descriptor() ([]byte, []int) {
	return file_proto_flow_proto_rawDescGZIP(), []int{1}
}

func (x *Records) GetEntries() []*Record {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DupMapEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Direction     Direction              `protobuf:"varint,2,opt,name=direction,proto3,enum=pbflow.Direction" json:"direction,omitempty"`
	Udn           string                 `protobuf:"bytes,3,opt,name=udn,proto3" json:"udn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DupMapEntry) Reset() {
	*x = DupMapEntry{}
	mi := &file_proto_flow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DupMapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DupMapEntry) ProtoMessage() {}

func (x *DupMapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DupMapEntry.ProtoReflect.Descriptor instead.
func (*DupMapEntry) Descriptor() ([]byte, []int) {
	return file_proto_flow_proto_rawDescGZIP(), []int{2}
}

func (x *DupMapEntry) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *DupMapEntry) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_INGRESS
}

func (x *DupMapEntry) GetUdn() string {
	if x != nil {
		return x.Udn
	}
	return ""
}

type NetworkEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        map[string]string      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkEvent) Reset() {
	*x = NetworkEvent{}
	mi := &file_proto_flow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEvent) ProtoMessage() {}

func (x *NetworkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEvent.ProtoReflect.Descriptor instead.
func (*NetworkEvent) Descriptor() ([]byte, []int) {
	return file_proto_flow_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkEvent) GetEvents() map[string]string {
	if x != nil {
		return x.Events
	}
	return nil
}

type Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocol as defined by ETH_P_* in linux/if_ether.h
	// https://github.com/torvalds/linux/blob/master/include/uapi/linux/if_ether.h
	EthProtocol   uint32                 `protobuf:"varint,1,opt,name=eth_protocol,json=ethProtocol,proto3" json:"eth_protocol,omitempty"`
	Direction     Direction              `protobuf:"varint,2,opt,name=direction,proto3,enum=pbflow.Direction" json:"direction,omitempty"`
	TimeFlowStart *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time_flow_start,json=timeFlowStart,proto3" json:"time_flow_start,omitempty"`
	TimeFlowEnd   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time_flow_end,json=timeFlowEnd,proto3" json:"time_flow_end,omitempty"`
	// OSI-layer attributes
	DataLink  *DataLink  `protobuf:"bytes,5,opt,name=data_link,json=dataLink,proto3" json:"data_link,omitempty"`
	Network   *Network   `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
	Transport *Transport `protobuf:"bytes,7,opt,name=transport,proto3" json:"transport,omitempty"`
	Bytes     uint64     `protobuf:"varint,8,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Packets   uint64     `protobuf:"varint,9,opt,name=packets,proto3" json:"packets,omitempty"`
	Interface string     `protobuf:"bytes,10,opt,name=interface,proto3" json:"interface,omitempty"`
	// Deprecated / unused
	Duplicate bool `protobuf:"varint,11,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	// Agent IP address to help identifying the source of the flow
	AgentIp                *IP                  `protobuf:"bytes,12,opt,name=agent_ip,json=agentIp,proto3" json:"agent_ip,omitempty"`
	Flags                  uint32               `protobuf:"varint,13,opt,name=flags,proto3" json:"flags,omitempty"`
	IcmpType               uint32               `protobuf:"varint,14,opt,name=icmp_type,json=icmpType,proto3" json:"icmp_type,omitempty"`
	IcmpCode               uint32               `protobuf:"varint,15,opt,name=icmp_code,json=icmpCode,proto3" json:"icmp_code,omitempty"`
	PktDropBytes           uint64               `protobuf:"varint,16,opt,name=pkt_drop_bytes,json=pktDropBytes,proto3" json:"pkt_drop_bytes,omitempty"`
	PktDropPackets         uint64               `protobuf:"varint,17,opt,name=pkt_drop_packets,json=pktDropPackets,proto3" json:"pkt_drop_packets,omitempty"`
	PktDropLatestFlags     uint32               `protobuf:"varint,18,opt,name=pkt_drop_latest_flags,json=pktDropLatestFlags,proto3" json:"pkt_drop_latest_flags,omitempty"`
	PktDropLatestState     uint32               `protobuf:"varint,19,opt,name=pkt_drop_latest_state,json=pktDropLatestState,proto3" json:"pkt_drop_latest_state,omitempty"`
	PktDropLatestDropCause uint32               `protobuf:"varint,20,opt,name=pkt_drop_latest_drop_cause,json=pktDropLatestDropCause,proto3" json:"pkt_drop_latest_drop_cause,omitempty"`
	DnsId                  uint32               `protobuf:"varint,21,opt,name=dns_id,json=dnsId,proto3" json:"dns_id,omitempty"`
	DnsFlags               uint32               `protobuf:"varint,22,opt,name=dns_flags,json=dnsFlags,proto3" json:"dns_flags,omitempty"`
	DnsLatency             *durationpb.Duration `protobuf:"bytes,23,opt,name=dns_latency,json=dnsLatency,proto3" json:"dns_latency,omitempty"`
	TimeFlowRtt            *durationpb.Duration `protobuf:"bytes,24,opt,name=time_flow_rtt,json=timeFlowRtt,proto3" json:"time_flow_rtt,omitempty"`
	DnsErrno               uint32               `protobuf:"varint,25,opt,name=dns_errno,json=dnsErrno,proto3" json:"dns_errno,omitempty"`
	DupList                []*DupMapEntry       `protobuf:"bytes,26,rep,name=dup_list,json=dupList,proto3" json:"dup_list,omitempty"`
	NetworkEventsMetadata  []*NetworkEvent      `protobuf:"bytes,27,rep,name=network_events_metadata,json=networkEventsMetadata,proto3" json:"network_events_metadata,omitempty"`
	Xlat                   *Xlat                `protobuf:"bytes,28,opt,name=xlat,proto3" json:"xlat,omitempty"`
	Sampling               uint32               `protobuf:"varint,29,opt,name=sampling,proto3" json:"sampling,omitempty"`
	IpsecEncrypted         uint32               `protobuf:"varint,30,opt,name=ipsec_encrypted,json=ipsecEncrypted,proto3" json:"ipsec_encrypted,omitempty"`
	IpsecEncryptedRet      int32                `protobuf:"varint,31,opt,name=ipsec_encrypted_ret,json=ipsecEncryptedRet,proto3" json:"ipsec_encrypted_ret,omitempty"`
	DnsName                string               `protobuf:"bytes,32,opt,name=dns_name,json=dnsName,proto3" json:"dns_name,omitempty"`
	SslVersion             uint32               `protobuf:"varint,33,opt,name=ssl_version,json=sslVersion,proto3" json:"ssl_version,omitempty"`
	SslMismatch            bool                 `protobuf:"varint,34,opt,name=ssl_mismatch,json=sslMismatch,proto3" json:"ssl_mismatch,omitempty"`
	TlsTypes               uint32               `protobuf:"varint,35,opt,name=tls_types,json=tlsTypes,proto3" json:"tls_types,omitempty"`
	TlsCipherSuite         uint32               `protobuf:"varint,36,opt,name=tls_cipher_suite,json=tlsCipherSuite,proto3" json:"tls_cipher_suite,omitempty"`
	TlsKeyShare            uint32               `protobuf:"varint,37,opt,name=tls_key_share,json=tlsKeyShare,proto3" json:"tls_key_share,omitempty"`
	Quic                   *Quic                `protobuf:"bytes,38,opt,name=quic,proto3" json:"quic,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_proto_flow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_flow_proto_rawDescGZIP(), []int{4}
}

func (x *Record) GetEthProtocol() uint32 {
	if x != nil {
		return x.EthProtocol
	}
	return 0
}

func (x *Record) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_INGRESS
}

func (x *Record) GetTimeFlowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeFlowStart
	}
	return nil
}

func (x *Record) GetTimeFlowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeFlowEnd
	}
	return nil
}

func (x *Record) GetDataLink() *DataLink {
	if x != nil {
		return x.DataLink
	}
	return nil
}

func (x *Record) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *Record) GetTransport() *Transport {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *Record) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *Record) GetPackets() uint64 {
	if x != nil {
		return x.Packets
	}
	return 0
}

func (x *Record) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Record) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *Record) GetAgentIp() *IP {
	if x != nil {
		return x.AgentIp
	}
	return nil
}

func (x *Record) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Record) GetIcmpType() uint32 {
	if x != nil {
		return x.IcmpType
	}
	return 0
}

func (x *Record) GetIcmpCode() uint32 {
	if x != nil {
		return x.IcmpCode
	}
	return 0
}

func (x *Record) GetPktDropBytes() uint64 {
	if x != nil {
		return x.PktDropBytes
	}
	return 0
}

func (x *Record) GetPktDropPackets() uint64 {
	if x != nil {
		return x.PktDropPackets
	}
	return 0
}

func (x *Record) GetPktDropLatestFlags() uint32 {
	if x != nil {
		return x.PktDropLatestFlags
	}
	return 0
}

func (x *Record) GetPktDropLatestState() uint32 {
	if x != nil {
		return x.PktDropLatestState
	}
	return 0
}

func (x *Record) GetPktDropLatestDropCause() uint32 {
	if x != nil {
		return x.PktDropLatestDropCause
	}
	return 0
}

func (x *Record) GetDnsId() uint32 {
	if x != nil {
		return x.DnsId
	}
	return 0
}

func (x *Record) GetDnsFlags() uint32 {
	if x != nil {
		return x.DnsFlags
	}
	return 0
}

func (x *Record) GetDnsLatency() *durationpb.Duration {
	if x != nil {
		return x.DnsLatency
	}
	return nil
}

func (x *Record) GetTimeFlowRtt() *durationpb.Duration {
	if x != nil {
		return x.TimeFlowRtt
	}
	return nil
}

func (x *Record) GetDnsErrno() uint32 {
	if x != nil {
		return x.DnsErrno
	}
	return 0
}

func (x *Record) GetDupList() []*DupMapEntry {
	if x != nil {
		return x.DupList
	}
	return nil
}

func (x *Record) GetNetworkEventsMetadata() []*NetworkEvent {
	if x != nil {
		return x.NetworkEventsMetadata
	}
	return nil
}

func (x *Record) GetXlat() *Xlat {
	if x != nil {
		return x.Xlat
	}
	return nil
}

func (x *Record) GetSampling() uint32 {
	if x != nil {
		return x.Sampling
	}
	return 0
}

func (x *Record) GetIpsecEncrypted() uint32 {
	if x != nil {
		return x.IpsecEncrypted
	}
	return 0
}

func (x *Record) GetIpsecEncryptedRet() int32 {
	if x != nil {
		return x.IpsecEncryptedRet
	}
	return 0
}

func (x *Record) GetDnsName() string {
	if x != nil {
		return x.DnsName
	}
	return ""
}

func (x *Record) GetSslVersion() uint32 {
	if x != nil {
		return x.SslVersion
	}
	return 0
}

func (x *Record) GetSslMismatch() bool {
	if x != nil {
		return x.SslMismatch
	}
	return false
}

func (x *Record) GetTlsTypes() uint32 {
	if x != nil {
		return x.TlsTypes
	}
	return 0
}

func (x *Record) GetTlsCipherSuite() uint32 {
	if x != nil {
		return x.TlsCipherSuite
	}
	return 0
}

func (x *Record) GetTlsKeyShare() uint32 {
	if x != nil {
		return x.TlsKeyShare
	}
	return 0
}

func (x *Record) GetQuic() *Quic {
	if x != nil {
		return x.Quic
	}
	return nil
}

type DataLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcMac        uint64                 `protobuf:"varint,1,opt,name=src_mac,json=srcMac,proto3" json:"src_mac,omitempty"`
	DstMac        uint64                 `protobuf:"varint,2,opt,name=dst_mac,json=dstMac,proto3" json:"dst_mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataLink) Reset() {
	*x = DataLink{}
	mi := &file_proto_flow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataLink) ProtoMessage() {}

func (x *DataLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataLink.ProtoReflect.Descriptor instead.
func (*DataLink) Descriptor() ([]byte, []int) {
	return file_proto_flow_proto_rawDescGZIP(), []int{5}
}

func (x *DataLink) GetSrcMac() uint64 {
	if x != nil {
		return x.SrcMac
	}
	return 0
}

func (x *DataLink) GetDstMac() uint64 {
	if x != nil {
		return x.DstMac
	}
	return 0
}

type Network struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcAddr       *IP                    `protobuf:"bytes,1,opt,name=src_addr,json=srcAddr,proto3" json:"src_addr,omitempty"`
	DstAddr       *IP                    `protobuf:"bytes,2,opt,name=dst_addr,json=dstAddr,proto3" json:"dst_addr,omitempty"`
	Dscp          uint32                 `protobuf:"varint,3,opt,name=dscp,proto3" json:"dscp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_proto_flow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_proto_flow_proto_rawDescGZIP(), []int{6}
}

func (x *Network) GetSrcAddr() *IP {
	if x != nil {
		return x.SrcAddr
	}
	return nil
}

func (x *Network) GetDstAddr() *IP {
	if x != nil {
		return x.DstAddr
	}
	return nil
}

func (x *Network) GetDscp() uint32 {
	if x != nil {
		return x.Dscp
	}
	return 0
}

type IP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to IpFamily:
	//
	//	*IP_Ipv4
	//	*IP_Ipv6
	IpFamily      isIP_IpFamily `protobuf_oneof:"ip_family"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IP) Reset() {
	*x = IP{}
	mi := &file_proto_flow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IP) ProtoMessage() {}

func (x *IP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IP.ProtoReflect.Descriptor instead.
func (*IP) Descriptor() ([]byte, []int) {
	return file_proto_flow_proto_rawDescGZIP(), []int{7}
}

func (x *IP) GetIpFamily() isIP_IpFamily {
	if x != nil {
		return x.IpFamily
	}
	return nil
}

func (x *IP) GetIpv4() uint32 {
	if x != nil {
		if x, ok := x.IpFamily.(*IP_Ipv4); ok {
			return x.Ipv4
		}
	}
	return 0
}

func (x *IP) GetIpv6() []byte {
	if x != nil {
		if x, ok := x.IpFamily.(*IP_Ipv6); ok {
			return x.Ipv6
		}
	}
	return nil
}

type isIP_IpFamily interface {
	isIP_IpFamily()
}

type IP_Ipv4 struct {
	Ipv4 uint32 `protobuf:"fixed32,1,opt,name=ipv4,proto3,oneof"`
}

type IP_Ipv6 struct {
	Ipv6 []byte `protobuf:"bytes,2,opt,name=ipv6,proto3,oneof"`
}

func (*IP_Ipv4) isIP_IpFamily() {}

func (*IP_Ipv6) isIP_IpFamily() {}

type Transport struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	SrcPort uint32                 `protobuf:"varint,1,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort uint32                 `protobuf:"varint,2,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	// protocol as defined by IPPROTO_* in linux/in.h
	// https://github.com/torvalds/linux/blob/master/include/uapi/linux/in.h
	Protocol      uint32 `protobuf:"varint,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport) Reset() {
	*x = Transport{}
	mi := &file_proto_flow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport) ProtoMessage() {}

func (x *Transport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport.ProtoReflect.Descriptor instead.
func (*Transport) Descriptor() ([]byte, []int) {
	return file_proto_flow_proto_rawDescGZIP(), []int{8}
}

func (x *Transport) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *Transport) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *Transport) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

type Xlat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcAddr       *IP                    `protobuf:"bytes,1,opt,name=src_addr,json=srcAddr,proto3" json:"src_addr,omitempty"`
	DstAddr       *IP                    `protobuf:"bytes,2,opt,name=dst_addr,json=dstAddr,proto3" json:"dst_addr,omitempty"`
	SrcPort       uint32                 `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort       uint32                 `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	ZoneId        uint32                 `protobuf:"varint,5,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Xlat) Reset() {
	*x = Xlat{}
	mi := &file_proto_flow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Xlat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Xlat) ProtoMessage() {}

func (x *Xlat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Xlat.ProtoReflect.Descriptor instead.
func (*Xlat) Descriptor() ([]byte, []int) {
	return file_proto_flow_proto_rawDescGZIP(), []int{9}
}

func (x *Xlat) GetSrcAddr() *IP {
	if x != nil {
		return x.SrcAddr
	}
	return nil
}

func (x *Xlat) GetDstAddr() *IP {
	if x != nil {
		return x.DstAddr
	}
	return nil
}

func (x *Xlat) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *Xlat) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *Xlat) GetZoneId() uint32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

type Quic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	SeenLongHdr   uint32                 `protobuf:"varint,2,opt,name=seen_long_hdr,json=seenLongHdr,proto3" json:"seen_long_hdr,omitempty"`
	SeenShortHdr  uint32                 `protobuf:"varint,3,opt,name=seen_short_hdr,json=seenShortHdr,proto3" json:"seen_short_hdr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quic) Reset() {
	*x = Quic{}
	mi := &file_proto_flow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quic) ProtoMessage() {}

func (x *Quic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quic.ProtoReflect.Descriptor instead.
func (*Quic) Descriptor() ([]byte, []int) {
	return file_proto_flow_proto_rawDescGZIP(), []int{10}
}

func (x *Quic) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Quic) GetSeenLongHdr() uint32 {
	if x != nil {
		return x.SeenLongHdr
	}
	return 0
}

func (x *Quic) GetSeenShortHdr() uint32 {
	if x != nil {
		return x.SeenShortHdr
	}
	return 0
}

var File_proto_flow_proto protoreflect.FileDescriptor

const file_proto_flow_proto_rawDesc = "" +
	"\n" +
	"\x10proto/flow.proto\x12\x06pbflow\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x10\n" +
	"\x0eCollectorReply\"3\n" +
	"\aRecords\x12(\n" +
	"\aentries\x18\x01 \x03(\v2\x0e.pbflow.RecordR\aentries\"n\n" +
	"\vDupMapEntry\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12/\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x11.pbflow.DirectionR\tdirection\x12\x10\n" +
	"\x03udn\x18\x03 \x01(\tR\x03udn\"\x83\x01\n" +
	"\fNetworkEvent\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .pbflow.NetworkEvent.EventsEntryR\x06events\x1a9\n" +
	"\vEventsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\f\n" +
	"\x06Record\x12!\n" +
	"\feth_protocol\x18\x01 \x01(\rR\vethProtocol\x12/\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x11.pbflow.DirectionR\tdirection\x12B\n" +
	"\x0ftime_flow_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rtimeFlowStart\x12>\n" +
	"\rtime_flow_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vtimeFlowEnd\x12-\n" +
	"\tdata_link\x18\x05 \x01(\v2\x10.pbflow.DataLinkR\bdataLink\x12)\n" +
	"\anetwork\x18\x06 \x01(\v2\x0f.pbflow.NetworkR\anetwork\x12/\n" +
	"\ttransport\x18\a \x01(\v2\x11.pbflow.TransportR\ttransport\x12\x14\n" +
	"\x05bytes\x18\b \x01(\x04R\x05bytes\x12\x18\n" +
	"\apackets\x18\t \x01(\x04R\apackets\x12\x1c\n" +
	"\tinterface\x18\n" +
	" \x01(\tR\tinterface\x12\x1c\n" +
	"\tduplicate\x18\v \x01(\bR\tduplicate\x12%\n" +
	"\bagent_ip\x18\f \x01(\v2\n" +
	".pbflow.IPR\aagentIp\x12\x14\n" +
	"\x05flags\x18\r \x01(\rR\x05flags\x12\x1b\n" +
	"\ticmp_type\x18\x0e \x01(\rR\bicmpType\x12\x1b\n" +
	"\ticmp_code\x18\x0f \x01(\rR\bicmpCode\x12$\n" +
	"\x0epkt_drop_bytes\x18\x10 \x01(\x04R\fpktDropBytes\x12(\n" +
	"\x10pkt_drop_packets\x18\x11 \x01(\x04R\x0epktDropPackets\x121\n" +
	"\x15pkt_drop_latest_flags\x18\x12 \x01(\rR\x12pktDropLatestFlags\x121\n" +
	"\x15pkt_drop_latest_state\x18\x13 \x01(\rR\x12pktDropLatestState\x12:\n" +
	"\x1apkt_drop_latest_drop_cause\x18\x14 \x01(\rR\x16pktDropLatestDropCause\x12\x15\n" +
	"\x06dns_id\x18\x15 \x01(\rR\x05dnsId\x12\x1b\n" +
	"\tdns_flags\x18\x16 \x01(\rR\bdnsFlags\x12:\n" +
	"\vdns_latency\x18\x17 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"dnsLatency\x12=\n" +
	"\rtime_flow_rtt\x18\x18 \x01(\v2\x19.google.protobuf.DurationR\vtimeFlowRtt\x12\x1b\n" +
	"\tdns_errno\x18\x19 \x01(\rR\bdnsErrno\x12.\n" +
	"\bdup_list\x18\x1a \x03(\v2\x13.pbflow.DupMapEntryR\adupList\x12L\n" +
	"\x17network_events_metadata\x18\x1b \x03(\v2\x14.pbflow.NetworkEventR\x15networkEventsMetadata\x12 \n" +
	"\x04xlat\x18\x1c \x01(\v2\f.pbflow.XlatR\x04xlat\x12\x1a\n" +
	"\bsampling\x18\x1d \x01(\rR\bsampling\x12'\n" +
	"\x0fipsec_encrypted\x18\x1e \x01(\rR\x0eipsecEncrypted\x12.\n" +
	"\x13ipsec_encrypted_ret\x18\x1f \x01(\x05R\x11ipsecEncryptedRet\x12\x19\n" +
	"\bdns_name\x18  \x01(\tR\adnsName\x12\x1f\n" +
	"\vssl_version\x18! \x01(\rR\n" +
	"sslVersion\x12!\n" +
	"\fssl_mismatch\x18\" \x01(\bR\vsslMismatch\x12\x1b\n" +
	"\ttls_types\x18# \x01(\rR\btlsTypes\x12(\n" +
	"\x10tls_cipher_suite\x18$ \x01(\rR\x0etlsCipherSuite\x12\"\n" +
	"\rtls_key_share\x18% \x01(\rR\vtlsKeyShare\x12 \n" +
	"\x04quic\x18& \x01(\v2\f.pbflow.QuicR\x04quic\"<\n" +
	"\bDataLink\x12\x17\n" +
	"\asrc_mac\x18\x01 \x01(\x04R\x06srcMac\x12\x17\n" +
	"\adst_mac\x18\x02 \x01(\x04R\x06dstMac\"k\n" +
	"\aNetwork\x12%\n" +
	"\bsrc_addr\x18\x01 \x01(\v2\n" +
	".pbflow.IPR\asrcAddr\x12%\n" +
	"\bdst_addr\x18\x02 \x01(\v2\n" +
	".pbflow.IPR\adstAddr\x12\x12\n" +
	"\x04dscp\x18\x03 \x01(\rR\x04dscp\"=\n" +
	"\x02IP\x12\x14\n" +
	"\x04ipv4\x18\x01 \x01(\aH\x00R\x04ipv4\x12\x14\n" +
	"\x04ipv6\x18\x02 \x01(\fH\x00R\x04ipv6B\v\n" +
	"\tip_family\"]\n" +
	"\tTransport\x12\x19\n" +
	"\bsrc_port\x18\x01 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x02 \x01(\rR\adstPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\rR\bprotocol\"\xa3\x01\n" +
	"\x04Xlat\x12%\n" +
	"\bsrc_addr\x18\x01 \x01(\v2\n" +
	".pbflow.IPR\asrcAddr\x12%\n" +
	"\bdst_addr\x18\x02 \x01(\v2\n" +
	".pbflow.IPR\adstAddr\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x04 \x01(\rR\adstPort\x12\x17\n" +
	"\azone_id\x18\x05 \x01(\rR\x06zoneId\"j\n" +
	"\x04Quic\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\"\n" +
	"\rseen_long_hdr\x18\x02 \x01(\rR\vseenLongHdr\x12$\n" +
	"\x0eseen_short_hdr\x18\x03 \x01(\rR\fseenShortHdr*$\n" +
	"\tDirection\x12\v\n" +
	"\aINGRESS\x10\x00\x12\n" +
	"\n" +
	"\x06EGRESS\x10\x012>\n" +
	"\tCollector\x121\n" +
	"\x04Send\x12\x0f.pbflow.Records\x1a\x16.pbflow.CollectorReply\"\x00B\x12Z\x10./pb/flow;pbflowb\x06proto3"

var (
	file_proto_flow_proto_rawDescOnce sync.Once
	file_proto_flow_proto_rawDescData []byte
)

func file_proto_flow_proto_rawDescGZIP() []byte {
	file_proto_flow_proto_rawDescOnce.Do(func() {
		file_proto_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_flow_proto_rawDesc), len(file_proto_flow_proto_rawDesc)))
	})
	return file_proto_flow_proto_rawDescData
}

var file_proto_flow_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_flow_proto_goTypes = []any{
	(Direction)(0),                // 0: pbflow.Direction
	(*CollectorReply)(nil),        // 1: pbflow.CollectorReply
	(*Records)(nil),               // 2: pbflow.Records
	(*DupMapEntry)(nil),           // 3: pbflow.DupMapEntry
	(*NetworkEvent)(nil),          // 4: pbflow.NetworkEvent
	(*Record)(nil),                // 5: pbflow.Record
	(*DataLink)(nil),              // 6: pbflow.DataLink
	(*Network)(nil),               // 7: pbflow.Network
	(*IP)(nil),                    // 8: pbflow.IP
	(*Transport)(nil),             // 9: pbflow.Transport
	(*Xlat)(nil),                  // 10: pbflow.Xlat
	(*Quic)(nil),                  // 11: pbflow.Quic
	nil,                           // 12: pbflow.NetworkEvent.EventsEntry
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 14: google.protobuf.Duration
}
var file_proto_flow_proto_depIdxs = []int32{
	5,  // 0: pbflow.Records.entries:type_name -> pbflow.Record
	0,  // 1: pbflow.DupMapEntry.direction:type_name -> pbflow.Direction
	12, // 2: pbflow.NetworkEvent.events:type_name -> pbflow.NetworkEvent.EventsEntry
	0,  // 3: pbflow.Record.direction:type_name -> pbflow.Direction
	13, // 4: pbflow.Record.time_flow_start:type_name -> google.protobuf.Timestamp
	13, // 5: pbflow.Record.time_flow_end:type_name -> google.protobuf.Timestamp
	6,  // 6: pbflow.Record.data_link:type_name -> pbflow.DataLink
	7,  // 7: pbflow.Record.network:type_name -> pbflow.Network
	9,  // 8: pbflow.Record.transport:type_name -> pbflow.Transport
	8,  // 9: pbflow.Record.agent_ip:type_name -> pbflow.IP
	14, // 10: pbflow.Record.dns_latency:type_name -> google.protobuf.Duration
	14, // 11: pbflow.Record.time_flow_rtt:type_name -> google.protobuf.Duration
	3,  // 12: pbflow.Record.dup_list:type_name -> pbflow.DupMapEntry
	4,  // 13: pbflow.Record.network_events_metadata:type_name -> pbflow.NetworkEvent
	10, // 14: pbflow.Record.xlat:type_name -> pbflow.Xlat
	11, // 15: pbflow.Record.quic:type_name -> pbflow.Quic
	8,  // 16: pbflow.Network.src_addr:type_name -> pbflow.IP
	8,  // 17: pbflow.Network.dst_addr:type_name -> pbflow.IP
	8,  // 18: pbflow.Xlat.src_addr:type_name -> pbflow.IP
	8,  // 19: pbflow.Xlat.dst_addr:type_name -> pbflow.IP
	2,  // 20: pbflow.Collector.Send:input_type -> pbflow.Records
	1,  // 21: pbflow.Collector.Send:output_type -> pbflow.CollectorReply
	21, // [21:22] is the sub-list for method output_type
	20, // [20:21] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_flow_proto_init() }
func file_proto_flow_proto_init() {
	if File_proto_flow_proto != nil {
		return
	}
	file_proto_flow_proto_msgTypes[7].OneofWrappers = []any{
		(*IP_Ipv4)(nil),
		(*IP_Ipv6)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_flow_proto_rawDesc), len(file_proto_flow_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_flow_proto_goTypes,
		DependencyIndexes: file_proto_flow_proto_depIdxs,
		EnumInfos:         file_proto_flow_proto_enumTypes,
		MessageInfos:      file_proto_flow_proto_msgTypes,
	}.Build()
	File_proto_flow_proto = out.File
	file_proto_flow_proto_goTypes = nil
	file_proto_flow_proto_depIdxs = nil
}
