// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package flows

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type FlowsBpfAdditionalMetrics struct {
	_                 structs.HostLayout
	StartMonoTimeTs   uint64
	EndMonoTimeTs     uint64
	FlowRtt           uint64
	IpsecEncryptedRet int32
	EthProtocol       uint16
	IpsecEncrypted    bool
	_                 [1]byte
}

type FlowsBpfDirectionT uint32

const (
	FlowsBpfDirectionTINGRESS       FlowsBpfDirectionT = 0
	FlowsBpfDirectionTEGRESS        FlowsBpfDirectionT = 1
	FlowsBpfDirectionTMAX_DIRECTION FlowsBpfDirectionT = 2
)

type FlowsBpfDnsFlowId struct {
	_        structs.HostLayout
	SrcPort  uint16
	DstPort  uint16
	SrcIp    [16]uint8
	DstIp    [16]uint8
	Id       uint16
	Protocol uint8
	_        [1]byte
}

type FlowsBpfDnsMetrics FlowsBpfDnsMetricsT

type FlowsBpfDnsMetricsT struct {
	_               structs.HostLayout
	StartMonoTimeTs uint64
	EndMonoTimeTs   uint64
	Latency         uint64
	Id              uint16
	Flags           uint16
	EthProtocol     uint16
	Errno           uint8
	Name            [32]int8
	_               [1]byte
}

type FlowsBpfDnsNameBuffer struct {
	_    structs.HostLayout
	Name [32]int8
}

type FlowsBpfFilterActionT uint32

const (
	FlowsBpfFilterActionTACCEPT             FlowsBpfFilterActionT = 0
	FlowsBpfFilterActionTREJECT             FlowsBpfFilterActionT = 1
	FlowsBpfFilterActionTMAX_FILTER_ACTIONS FlowsBpfFilterActionT = 2
)

type FlowsBpfFilterKeyT struct {
	_         structs.HostLayout
	PrefixLen uint32
	IpData    [16]uint8
}

type FlowsBpfFilterValueT struct {
	_                 structs.HostLayout
	Protocol          uint8
	_                 [1]byte
	DstPortStart      uint16
	DstPortEnd        uint16
	DstPort1          uint16
	DstPort2          uint16
	SrcPortStart      uint16
	SrcPortEnd        uint16
	SrcPort1          uint16
	SrcPort2          uint16
	PortStart         uint16
	PortEnd           uint16
	Port1             uint16
	Port2             uint16
	IcmpType          uint8
	IcmpCode          uint8
	Direction         FlowsBpfDirectionT
	Action            FlowsBpfFilterActionT
	TcpFlags          FlowsBpfTcpFlagsT
	FilterDrops       uint8
	_                 [3]byte
	Sample            uint32
	DoPeerCIDR_lookup uint8
	_                 [3]byte
}

type FlowsBpfFlowId FlowsBpfFlowIdT

type FlowsBpfFlowIdT struct {
	_                 structs.HostLayout
	SrcIp             [16]uint8
	DstIp             [16]uint8
	SrcPort           uint16
	DstPort           uint16
	TransportProtocol uint8
	IcmpType          uint8
	IcmpCode          uint8
	_                 [1]byte
}

type FlowsBpfFlowMetrics FlowsBpfFlowMetricsT

type FlowsBpfFlowMetricsT struct {
	_                structs.HostLayout
	StartMonoTimeTs  uint64
	EndMonoTimeTs    uint64
	Bytes            uint64
	Packets          uint32
	EthProtocol      uint16
	Flags            uint16
	SrcMac           [6]uint8
	DstMac           [6]uint8
	IfIndexFirstSeen uint32
	Lock             struct {
		_   structs.HostLayout
		Val uint32
	}
	Sampling           uint32
	DirectionFirstSeen uint8
	Errno              uint8
	Dscp               uint8
	NbObservedIntf     uint8
	ObservedDirection  [6]uint8
	_                  [2]byte
	ObservedIntf       [6]uint32
	SslVersion         uint16
	TlsCipherSuite     uint16
	TlsKeyShare        uint16
	TlsTypes           uint8
	MiscFlags          uint8
	_                  [4]byte
}

type FlowsBpfFlowRecordT struct {
	_       structs.HostLayout
	Id      FlowsBpfFlowId
	Metrics FlowsBpfFlowMetrics
}

type FlowsBpfGlobalCountersKeyT uint32

const (
	FlowsBpfGlobalCountersKeyTHASHMAP_FAIL_UPDATE_FLOW            FlowsBpfGlobalCountersKeyT = 0
	FlowsBpfGlobalCountersKeyTHASHMAP_FAIL_CREATE_FLOW            FlowsBpfGlobalCountersKeyT = 1
	FlowsBpfGlobalCountersKeyTHASHMAP_FAIL_UPDATE_DNS             FlowsBpfGlobalCountersKeyT = 2
	FlowsBpfGlobalCountersKeyTFILTER_REJECT                       FlowsBpfGlobalCountersKeyT = 3
	FlowsBpfGlobalCountersKeyTFILTER_ACCEPT                       FlowsBpfGlobalCountersKeyT = 4
	FlowsBpfGlobalCountersKeyTFILTER_NOMATCH                      FlowsBpfGlobalCountersKeyT = 5
	FlowsBpfGlobalCountersKeyTNETWORK_EVENTS_ERR                  FlowsBpfGlobalCountersKeyT = 6
	FlowsBpfGlobalCountersKeyTNETWORK_EVENTS_ERR_GROUPID_MISMATCH FlowsBpfGlobalCountersKeyT = 7
	FlowsBpfGlobalCountersKeyTNETWORK_EVENTS_ERR_UPDATE_MAP_FLOWS FlowsBpfGlobalCountersKeyT = 8
	FlowsBpfGlobalCountersKeyTNETWORK_EVENTS_GOOD                 FlowsBpfGlobalCountersKeyT = 9
	FlowsBpfGlobalCountersKeyTNETWORK_EVENTS_OVERFLOW             FlowsBpfGlobalCountersKeyT = 10
	FlowsBpfGlobalCountersKeyTNETWORK_EVENTS_COOKIE_TOO_BIG       FlowsBpfGlobalCountersKeyT = 11
	FlowsBpfGlobalCountersKeyTOBSERVED_INTF_MISSED                FlowsBpfGlobalCountersKeyT = 12
	FlowsBpfGlobalCountersKeyTMAX_COUNTERS                        FlowsBpfGlobalCountersKeyT = 13
)

type FlowsBpfNetworkEventsMetrics FlowsBpfNetworkEventsMetricsT

type FlowsBpfNetworkEventsMetricsT struct {
	_                structs.HostLayout
	StartMonoTimeTs  uint64
	EndMonoTimeTs    uint64
	NetworkEvents    [4][8]uint8
	Bytes            [4]uint16
	Packets          [4]uint16
	EthProtocol      uint16
	NetworkEventsIdx uint8
	_                [5]byte
}

type FlowsBpfPktDropMetrics FlowsBpfPktDropMetricsT

type FlowsBpfPktDropMetricsT struct {
	_               structs.HostLayout
	StartMonoTimeTs uint64
	EndMonoTimeTs   uint64
	Bytes           uint16
	Packets         uint16
	LatestDropCause uint32
	LatestFlags     uint16
	EthProtocol     uint16
	LatestState     uint8
	_               [3]byte
}

type FlowsBpfQuicConfigT uint32

const (
	FlowsBpfQuicConfigTQUIC_CONFIG_DISABLED     FlowsBpfQuicConfigT = 0
	FlowsBpfQuicConfigTQUIC_CONFIG_ENABLED      FlowsBpfQuicConfigT = 1
	FlowsBpfQuicConfigTQUIC_CONFIG_ANY_UDP_PORT FlowsBpfQuicConfigT = 2
)

type FlowsBpfQuicMetrics FlowsBpfQuicMetricsT

type FlowsBpfQuicMetricsT struct {
	_               structs.HostLayout
	StartMonoTimeTs uint64
	EndMonoTimeTs   uint64
	Version         uint32
	EthProtocol     uint16
	SeenLongHdr     uint8
	SeenShortHdr    uint8
}

type FlowsBpfTcpFlagsT uint32

const (
	FlowsBpfTcpFlagsTFIN_FLAG     FlowsBpfTcpFlagsT = 1
	FlowsBpfTcpFlagsTSYN_FLAG     FlowsBpfTcpFlagsT = 2
	FlowsBpfTcpFlagsTRST_FLAG     FlowsBpfTcpFlagsT = 4
	FlowsBpfTcpFlagsTPSH_FLAG     FlowsBpfTcpFlagsT = 8
	FlowsBpfTcpFlagsTACK_FLAG     FlowsBpfTcpFlagsT = 16
	FlowsBpfTcpFlagsTURG_FLAG     FlowsBpfTcpFlagsT = 32
	FlowsBpfTcpFlagsTECE_FLAG     FlowsBpfTcpFlagsT = 64
	FlowsBpfTcpFlagsTCWR_FLAG     FlowsBpfTcpFlagsT = 128
	FlowsBpfTcpFlagsTSYN_ACK_FLAG FlowsBpfTcpFlagsT = 256
	FlowsBpfTcpFlagsTFIN_ACK_FLAG FlowsBpfTcpFlagsT = 512
	FlowsBpfTcpFlagsTRST_ACK_FLAG FlowsBpfTcpFlagsT = 1024
)

type FlowsBpfXlatMetrics FlowsBpfXlatMetricsT

type FlowsBpfXlatMetricsT struct {
	_               structs.HostLayout
	StartMonoTimeTs uint64
	EndMonoTimeTs   uint64
	Saddr           [16]uint8
	Daddr           [16]uint8
	Sport           uint16
	Dport           uint16
	ZoneId          uint16
	EthProtocol     uint16
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	FlowsBpfMapAdditionalFlowMetrics          = "additional_flow_metrics"
	FlowsBpfMapAggregatedFlows                = "aggregated_flows"
	FlowsBpfMapAggregatedFlowsDns             = "aggregated_flows_dns"
	FlowsBpfMapAggregatedFlowsNetworkEvents   = "aggregated_flows_network_events"
	FlowsBpfMapAggregatedFlowsPktDrop         = "aggregated_flows_pkt_drop"
	FlowsBpfMapAggregatedFlowsXlat            = "aggregated_flows_xlat"
	FlowsBpfMapDirectFlows                    = "direct_flows"
	FlowsBpfMapDnsFlows                       = "dns_flows"
	FlowsBpfMapDnsNameMap                     = "dns_name_map"
	FlowsBpfMapFilterMap                      = "filter_map"
	FlowsBpfMapGlobalCounters                 = "global_counters"
	FlowsBpfMapIpsecEgressMap                 = "ipsec_egress_map"
	FlowsBpfMapIpsecIngressMap                = "ipsec_ingress_map"
	FlowsBpfMapPeerFilterMap                  = "peer_filter_map"
	FlowsBpfMapQuicFlows                      = "quic_flows"
	FlowsBpfProgKfreeSkb                      = "kfree_skb"
	FlowsBpfProgNetkitPeerFlowParse           = "netkit_peer_flow_parse"
	FlowsBpfProgNetkitPrimaryFlowParse        = "netkit_primary_flow_parse"
	FlowsBpfProgNetworkEventsMonitoring       = "network_events_monitoring"
	FlowsBpfProgTcEgressFlowParse             = "tc_egress_flow_parse"
	FlowsBpfProgTcIngressFlowParse            = "tc_ingress_flow_parse"
	FlowsBpfProgTcpRcvFentry                  = "tcp_rcv_fentry"
	FlowsBpfProgTcpRcvKprobe                  = "tcp_rcv_kprobe"
	FlowsBpfProgTcxEgressFlowParse            = "tcx_egress_flow_parse"
	FlowsBpfProgTcxIngressFlowParse           = "tcx_ingress_flow_parse"
	FlowsBpfProgTrackNatManipPkt              = "track_nat_manip_pkt"
	FlowsBpfProgXfrmInputKprobe               = "xfrm_input_kprobe"
	FlowsBpfProgXfrmInputKretprobe            = "xfrm_input_kretprobe"
	FlowsBpfProgXfrmOutputKprobe              = "xfrm_output_kprobe"
	FlowsBpfProgXfrmOutputKretprobe           = "xfrm_output_kretprobe"
	FlowsBpfVarDnsPorts                       = "dns_ports"
	FlowsBpfVarDnsPortsCount                  = "dns_ports_count"
	FlowsBpfVarEnableDirectflowsRingbuf       = "enable_directflows_ringbuf"
	FlowsBpfVarEnableDnsTracking              = "enable_dns_tracking"
	FlowsBpfVarEnableFiltering                = "enable_filtering"
	FlowsBpfVarEnableIpsec                    = "enable_ipsec"
	FlowsBpfVarEnableNetworkEventsMonitoring  = "enable_network_events_monitoring"
	FlowsBpfVarEnablePktTranslationTracking   = "enable_pkt_translation_tracking"
	FlowsBpfVarEnableQuicTracking             = "enable_quic_tracking"
	FlowsBpfVarEnableRtt                      = "enable_rtt"
	FlowsBpfVarEnableTlsUsageTracking         = "enable_tls_usage_tracking"
	FlowsBpfVarFilterKey                      = "filter_key"
	FlowsBpfVarFilterValue                    = "filter_value"
	FlowsBpfVarHasFilterSampling              = "has_filter_sampling"
	FlowsBpfVarNetworkEventsMonitoringGroupid = "network_events_monitoring_groupid"
	FlowsBpfVarSampling                       = "sampling"
	FlowsBpfVarTraceMessages                  = "trace_messages"
	FlowsBpfVarUnusedCounters                 = "unused_counters"
	FlowsBpfVarUnusedFlowrec                  = "unused_flowrec"
)

// LoadFlowsBpf returns the embedded CollectionSpec for FlowsBpf.
func LoadFlowsBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FlowsBpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load FlowsBpf: %w", err)
	}

	return spec, err
}

// LoadFlowsBpfObjects loads FlowsBpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FlowsBpfObjects
//	*FlowsBpfPrograms
//	*FlowsBpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFlowsBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFlowsBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FlowsBpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FlowsBpfSpecs struct {
	FlowsBpfProgramSpecs
	FlowsBpfMapSpecs
	FlowsBpfVariableSpecs
}

// FlowsBpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FlowsBpfProgramSpecs struct {
	KfreeSkb                *ebpf.ProgramSpec `ebpf:"kfree_skb"`
	NetkitPeerFlowParse     *ebpf.ProgramSpec `ebpf:"netkit_peer_flow_parse"`
	NetkitPrimaryFlowParse  *ebpf.ProgramSpec `ebpf:"netkit_primary_flow_parse"`
	NetworkEventsMonitoring *ebpf.ProgramSpec `ebpf:"network_events_monitoring"`
	TcEgressFlowParse       *ebpf.ProgramSpec `ebpf:"tc_egress_flow_parse"`
	TcIngressFlowParse      *ebpf.ProgramSpec `ebpf:"tc_ingress_flow_parse"`
	TcpRcvFentry            *ebpf.ProgramSpec `ebpf:"tcp_rcv_fentry"`
	TcpRcvKprobe            *ebpf.ProgramSpec `ebpf:"tcp_rcv_kprobe"`
	TcxEgressFlowParse      *ebpf.ProgramSpec `ebpf:"tcx_egress_flow_parse"`
	TcxIngressFlowParse     *ebpf.ProgramSpec `ebpf:"tcx_ingress_flow_parse"`
	TrackNatManipPkt        *ebpf.ProgramSpec `ebpf:"track_nat_manip_pkt"`
	XfrmInputKprobe         *ebpf.ProgramSpec `ebpf:"xfrm_input_kprobe"`
	XfrmInputKretprobe      *ebpf.ProgramSpec `ebpf:"xfrm_input_kretprobe"`
	XfrmOutputKprobe        *ebpf.ProgramSpec `ebpf:"xfrm_output_kprobe"`
	XfrmOutputKretprobe     *ebpf.ProgramSpec `ebpf:"xfrm_output_kretprobe"`
}

// FlowsBpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FlowsBpfMapSpecs struct {
	AdditionalFlowMetrics        *ebpf.MapSpec `ebpf:"additional_flow_metrics"`
	AggregatedFlows              *ebpf.MapSpec `ebpf:"aggregated_flows"`
	AggregatedFlowsDns           *ebpf.MapSpec `ebpf:"aggregated_flows_dns"`
	AggregatedFlowsNetworkEvents *ebpf.MapSpec `ebpf:"aggregated_flows_network_events"`
	AggregatedFlowsPktDrop       *ebpf.MapSpec `ebpf:"aggregated_flows_pkt_drop"`
	AggregatedFlowsXlat          *ebpf.MapSpec `ebpf:"aggregated_flows_xlat"`
	DirectFlows                  *ebpf.MapSpec `ebpf:"direct_flows"`
	DnsFlows                     *ebpf.MapSpec `ebpf:"dns_flows"`
	DnsNameMap                   *ebpf.MapSpec `ebpf:"dns_name_map"`
	FilterMap                    *ebpf.MapSpec `ebpf:"filter_map"`
	GlobalCounters               *ebpf.MapSpec `ebpf:"global_counters"`
	IpsecEgressMap               *ebpf.MapSpec `ebpf:"ipsec_egress_map"`
	IpsecIngressMap              *ebpf.MapSpec `ebpf:"ipsec_ingress_map"`
	PeerFilterMap                *ebpf.MapSpec `ebpf:"peer_filter_map"`
	QuicFlows                    *ebpf.MapSpec `ebpf:"quic_flows"`
}

// FlowsBpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FlowsBpfVariableSpecs struct {
	DnsPorts                       *ebpf.VariableSpec `ebpf:"dns_ports"`
	DnsPortsCount                  *ebpf.VariableSpec `ebpf:"dns_ports_count"`
	EnableDirectflowsRingbuf       *ebpf.VariableSpec `ebpf:"enable_directflows_ringbuf"`
	EnableDnsTracking              *ebpf.VariableSpec `ebpf:"enable_dns_tracking"`
	EnableFiltering                *ebpf.VariableSpec `ebpf:"enable_filtering"`
	EnableIpsec                    *ebpf.VariableSpec `ebpf:"enable_ipsec"`
	EnableNetworkEventsMonitoring  *ebpf.VariableSpec `ebpf:"enable_network_events_monitoring"`
	EnablePktTranslationTracking   *ebpf.VariableSpec `ebpf:"enable_pkt_translation_tracking"`
	EnableQuicTracking             *ebpf.VariableSpec `ebpf:"enable_quic_tracking"`
	EnableRtt                      *ebpf.VariableSpec `ebpf:"enable_rtt"`
	EnableTlsUsageTracking         *ebpf.VariableSpec `ebpf:"enable_tls_usage_tracking"`
	FilterKey                      *ebpf.VariableSpec `ebpf:"filter_key"`
	FilterValue                    *ebpf.VariableSpec `ebpf:"filter_value"`
	HasFilterSampling              *ebpf.VariableSpec `ebpf:"has_filter_sampling"`
	NetworkEventsMonitoringGroupid *ebpf.VariableSpec `ebpf:"network_events_monitoring_groupid"`
	Sampling                       *ebpf.VariableSpec `ebpf:"sampling"`
	TraceMessages                  *ebpf.VariableSpec `ebpf:"trace_messages"`
	UnusedCounters                 *ebpf.VariableSpec `ebpf:"unused_counters"`
	UnusedFlowrec                  *ebpf.VariableSpec `ebpf:"unused_flowrec"`
}

// FlowsBpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFlowsBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type FlowsBpfObjects struct {
	FlowsBpfPrograms
	FlowsBpfMaps
	FlowsBpfVariables
}

func (o *FlowsBpfObjects) Close() error {
	return _FlowsBpfClose(
		&o.FlowsBpfPrograms,
		&o.FlowsBpfMaps,
	)
}

// FlowsBpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFlowsBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type FlowsBpfMaps struct {
	AdditionalFlowMetrics        *ebpf.Map `ebpf:"additional_flow_metrics"`
	AggregatedFlows              *ebpf.Map `ebpf:"aggregated_flows"`
	AggregatedFlowsDns           *ebpf.Map `ebpf:"aggregated_flows_dns"`
	AggregatedFlowsNetworkEvents *ebpf.Map `ebpf:"aggregated_flows_network_events"`
	AggregatedFlowsPktDrop       *ebpf.Map `ebpf:"aggregated_flows_pkt_drop"`
	AggregatedFlowsXlat          *ebpf.Map `ebpf:"aggregated_flows_xlat"`
	DirectFlows                  *ebpf.Map `ebpf:"direct_flows"`
	DnsFlows                     *ebpf.Map `ebpf:"dns_flows"`
	DnsNameMap                   *ebpf.Map `ebpf:"dns_name_map"`
	FilterMap                    *ebpf.Map `ebpf:"filter_map"`
	GlobalCounters               *ebpf.Map `ebpf:"global_counters"`
	IpsecEgressMap               *ebpf.Map `ebpf:"ipsec_egress_map"`
	IpsecIngressMap              *ebpf.Map `ebpf:"ipsec_ingress_map"`
	PeerFilterMap                *ebpf.Map `ebpf:"peer_filter_map"`
	QuicFlows                    *ebpf.Map `ebpf:"quic_flows"`
}

func (m *FlowsBpfMaps) Close() error {
	return _FlowsBpfClose(
		m.AdditionalFlowMetrics,
		m.AggregatedFlows,
		m.AggregatedFlowsDns,
		m.AggregatedFlowsNetworkEvents,
		m.AggregatedFlowsPktDrop,
		m.AggregatedFlowsXlat,
		m.DirectFlows,
		m.DnsFlows,
		m.DnsNameMap,
		m.FilterMap,
		m.GlobalCounters,
		m.IpsecEgressMap,
		m.IpsecIngressMap,
		m.PeerFilterMap,
		m.QuicFlows,
	)
}

// FlowsBpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadFlowsBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type FlowsBpfVariables struct {
	DnsPorts                       *ebpf.Variable `ebpf:"dns_ports"`
	DnsPortsCount                  *ebpf.Variable `ebpf:"dns_ports_count"`
	EnableDirectflowsRingbuf       *ebpf.Variable `ebpf:"enable_directflows_ringbuf"`
	EnableDnsTracking              *ebpf.Variable `ebpf:"enable_dns_tracking"`
	EnableFiltering                *ebpf.Variable `ebpf:"enable_filtering"`
	EnableIpsec                    *ebpf.Variable `ebpf:"enable_ipsec"`
	EnableNetworkEventsMonitoring  *ebpf.Variable `ebpf:"enable_network_events_monitoring"`
	EnablePktTranslationTracking   *ebpf.Variable `ebpf:"enable_pkt_translation_tracking"`
	EnableQuicTracking             *ebpf.Variable `ebpf:"enable_quic_tracking"`
	EnableRtt                      *ebpf.Variable `ebpf:"enable_rtt"`
	EnableTlsUsageTracking         *ebpf.Variable `ebpf:"enable_tls_usage_tracking"`
	FilterKey                      *ebpf.Variable `ebpf:"filter_key"`
	FilterValue                    *ebpf.Variable `ebpf:"filter_value"`
	HasFilterSampling              *ebpf.Variable `ebpf:"has_filter_sampling"`
	NetworkEventsMonitoringGroupid *ebpf.Variable `ebpf:"network_events_monitoring_groupid"`
	Sampling                       *ebpf.Variable `ebpf:"sampling"`
	TraceMessages                  *ebpf.Variable `ebpf:"trace_messages"`
	UnusedCounters                 *ebpf.Variable `ebpf:"unused_counters"`
	UnusedFlowrec                  *ebpf.Variable `ebpf:"unused_flowrec"`
}

// FlowsBpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFlowsBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type FlowsBpfPrograms struct {
	KfreeSkb                *ebpf.Program `ebpf:"kfree_skb"`
	NetkitPeerFlowParse     *ebpf.Program `ebpf:"netkit_peer_flow_parse"`
	NetkitPrimaryFlowParse  *ebpf.Program `ebpf:"netkit_primary_flow_parse"`
	NetworkEventsMonitoring *ebpf.Program `ebpf:"network_events_monitoring"`
	TcEgressFlowParse       *ebpf.Program `ebpf:"tc_egress_flow_parse"`
	TcIngressFlowParse      *ebpf.Program `ebpf:"tc_ingress_flow_parse"`
	TcpRcvFentry            *ebpf.Program `ebpf:"tcp_rcv_fentry"`
	TcpRcvKprobe            *ebpf.Program `ebpf:"tcp_rcv_kprobe"`
	TcxEgressFlowParse      *ebpf.Program `ebpf:"tcx_egress_flow_parse"`
	TcxIngressFlowParse     *ebpf.Program `ebpf:"tcx_ingress_flow_parse"`
	TrackNatManipPkt        *ebpf.Program `ebpf:"track_nat_manip_pkt"`
	XfrmInputKprobe         *ebpf.Program `ebpf:"xfrm_input_kprobe"`
	XfrmInputKretprobe      *ebpf.Program `ebpf:"xfrm_input_kretprobe"`
	XfrmOutputKprobe        *ebpf.Program `ebpf:"xfrm_output_kprobe"`
	XfrmOutputKretprobe     *ebpf.Program `ebpf:"xfrm_output_kretprobe"`
}

func (p *FlowsBpfPrograms) Close() error {
	return _FlowsBpfClose(
		p.KfreeSkb,
		p.NetkitPeerFlowParse,
		p.NetkitPrimaryFlowParse,
		p.NetworkEventsMonitoring,
		p.TcEgressFlowParse,
		p.TcIngressFlowParse,
		p.TcpRcvFentry,
		p.TcpRcvKprobe,
		p.TcxEgressFlowParse,
		p.TcxIngressFlowParse,
		p.TrackNatManipPkt,
		p.XfrmInputKprobe,
		p.XfrmInputKretprobe,
		p.XfrmOutputKprobe,
		p.XfrmOutputKretprobe,
	)
}

func _FlowsBpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed flowsbpf_arm64_bpfel.o
var _FlowsBpfBytes []byte
