// Code generated by bpf2go; DO NOT EDIT.
//go:build ppc64le

package packets

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type PacketsBpfFilterKeyT struct {
	_         structs.HostLayout
	PrefixLen uint32
	IpData    [16]uint8
}

type PacketsBpfFilterValueT struct {
	_                 structs.HostLayout
	Protocol          uint8
	_                 [1]byte
	DstPortStart      uint16
	DstPortEnd        uint16
	DstPort1          uint16
	DstPort2          uint16
	SrcPortStart      uint16
	SrcPortEnd        uint16
	SrcPort1          uint16
	SrcPort2          uint16
	PortStart         uint16
	PortEnd           uint16
	Port1             uint16
	Port2             uint16
	IcmpType          uint8
	IcmpCode          uint8
	Direction         uint32
	Action            uint32
	TcpFlags          uint32
	FilterDrops       uint8
	_                 [3]byte
	Sample            uint32
	DoPeerCIDR_lookup uint8
	_                 [3]byte
}

type PacketsBpfSslDataEventT struct {
	_           structs.HostLayout
	TimestampNs uint64
	PidTgid     uint64
	DataLen     int32
	SslType     uint8
	Direction   uint8
	TlsSource   uint8
	TupleValid  uint8
	SrcPort     uint16
	DstPort     uint16
	SrcAddr     [16]uint8
	DstAddr     [16]uint8
	SocketFd    int32
	ConnUserPtr uint64
	Data        [16384]int8
}

type PacketsBpfSslFdKeyT struct {
	_      structs.HostLayout
	SslPtr uint64
	Tgid   uint32
	Pad    uint32
}

type PacketsBpfSslFdPendingT struct {
	_   structs.HostLayout
	Key PacketsBpfSslFdKeyT
	Fd  int32
	_   [4]byte
}

type PacketsBpfSslReadActiveT struct {
	_           structs.HostLayout
	SslType     uint8
	Pad         [7]uint8
	BufUser     uint64
	ConnUserPtr uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	PacketsBpfMapFilterMap                 = "filter_map"
	PacketsBpfMapGlobalCounters            = "global_counters"
	PacketsBpfMapPacketRecord              = "packet_record"
	PacketsBpfMapPeerFilterMap             = "peer_filter_map"
	PacketsBpfMapSslDataEventMap           = "ssl_data_event_map"
	PacketsBpfMapSslFdMap                  = "ssl_fd_map"
	PacketsBpfMapSslFdPendingMap           = "ssl_fd_pending_map"
	PacketsBpfMapSslReadActiveMap          = "ssl_read_active_map"
	PacketsBpfProgNetkitPeerPacketParse    = "netkit_peer_packet_parse"
	PacketsBpfProgNetkitPrimaryPacketParse = "netkit_primary_packet_parse"
	PacketsBpfProgProbeEntrySSL_free       = "probe_entry_SSL_free"
	PacketsBpfProgProbeEntrySSL_read       = "probe_entry_SSL_read"
	PacketsBpfProgProbeEntrySSL_setFd      = "probe_entry_SSL_set_fd"
	PacketsBpfProgProbeEntrySSL_write      = "probe_entry_SSL_write"
	PacketsBpfProgProbeRetSSL_read         = "probe_ret_SSL_read"
	PacketsBpfProgProbeRetSSL_setFd        = "probe_ret_SSL_set_fd"
	PacketsBpfProgTcEgressPacketParse      = "tc_egress_packet_parse"
	PacketsBpfProgTcIngressPacketParse     = "tc_ingress_packet_parse"
	PacketsBpfProgTcxEgressPacketParse     = "tcx_egress_packet_parse"
	PacketsBpfProgTcxIngressPacketParse    = "tcx_ingress_packet_parse"
	PacketsBpfVarEnableFiltering           = "enable_filtering"
	PacketsBpfVarEnableOpensslTracking     = "enable_openssl_tracking"
	PacketsBpfVarFilterKey                 = "filter_key"
	PacketsBpfVarFilterValue               = "filter_value"
	PacketsBpfVarSampling                  = "sampling"
	PacketsBpfVarSslDataEvent              = "ssl_data_event"
	PacketsBpfVarTraceMessages             = "trace_messages"
	PacketsBpfVarUnusedCounters            = "unused_counters"
)

// LoadPacketsBpf returns the embedded CollectionSpec for PacketsBpf.
func LoadPacketsBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PacketsBpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load PacketsBpf: %w", err)
	}

	return spec, err
}

// LoadPacketsBpfObjects loads PacketsBpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PacketsBpfObjects
//	*PacketsBpfPrograms
//	*PacketsBpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPacketsBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPacketsBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PacketsBpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PacketsBpfSpecs struct {
	PacketsBpfProgramSpecs
	PacketsBpfMapSpecs
	PacketsBpfVariableSpecs
}

// PacketsBpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PacketsBpfProgramSpecs struct {
	NetkitPeerPacketParse    *ebpf.ProgramSpec `ebpf:"netkit_peer_packet_parse"`
	NetkitPrimaryPacketParse *ebpf.ProgramSpec `ebpf:"netkit_primary_packet_parse"`
	ProbeEntrySSL_free       *ebpf.ProgramSpec `ebpf:"probe_entry_SSL_free"`
	ProbeEntrySSL_read       *ebpf.ProgramSpec `ebpf:"probe_entry_SSL_read"`
	ProbeEntrySSL_setFd      *ebpf.ProgramSpec `ebpf:"probe_entry_SSL_set_fd"`
	ProbeEntrySSL_write      *ebpf.ProgramSpec `ebpf:"probe_entry_SSL_write"`
	ProbeRetSSL_read         *ebpf.ProgramSpec `ebpf:"probe_ret_SSL_read"`
	ProbeRetSSL_setFd        *ebpf.ProgramSpec `ebpf:"probe_ret_SSL_set_fd"`
	TcEgressPacketParse      *ebpf.ProgramSpec `ebpf:"tc_egress_packet_parse"`
	TcIngressPacketParse     *ebpf.ProgramSpec `ebpf:"tc_ingress_packet_parse"`
	TcxEgressPacketParse     *ebpf.ProgramSpec `ebpf:"tcx_egress_packet_parse"`
	TcxIngressPacketParse    *ebpf.ProgramSpec `ebpf:"tcx_ingress_packet_parse"`
}

// PacketsBpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PacketsBpfMapSpecs struct {
	FilterMap        *ebpf.MapSpec `ebpf:"filter_map"`
	GlobalCounters   *ebpf.MapSpec `ebpf:"global_counters"`
	PacketRecord     *ebpf.MapSpec `ebpf:"packet_record"`
	PeerFilterMap    *ebpf.MapSpec `ebpf:"peer_filter_map"`
	SslDataEventMap  *ebpf.MapSpec `ebpf:"ssl_data_event_map"`
	SslFdMap         *ebpf.MapSpec `ebpf:"ssl_fd_map"`
	SslFdPendingMap  *ebpf.MapSpec `ebpf:"ssl_fd_pending_map"`
	SslReadActiveMap *ebpf.MapSpec `ebpf:"ssl_read_active_map"`
}

// PacketsBpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PacketsBpfVariableSpecs struct {
	EnableFiltering       *ebpf.VariableSpec `ebpf:"enable_filtering"`
	EnableOpensslTracking *ebpf.VariableSpec `ebpf:"enable_openssl_tracking"`
	FilterKey             *ebpf.VariableSpec `ebpf:"filter_key"`
	FilterValue           *ebpf.VariableSpec `ebpf:"filter_value"`
	Sampling              *ebpf.VariableSpec `ebpf:"sampling"`
	SslDataEvent          *ebpf.VariableSpec `ebpf:"ssl_data_event"`
	TraceMessages         *ebpf.VariableSpec `ebpf:"trace_messages"`
	UnusedCounters        *ebpf.VariableSpec `ebpf:"unused_counters"`
}

// PacketsBpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPacketsBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type PacketsBpfObjects struct {
	PacketsBpfPrograms
	PacketsBpfMaps
	PacketsBpfVariables
}

func (o *PacketsBpfObjects) Close() error {
	return _PacketsBpfClose(
		&o.PacketsBpfPrograms,
		&o.PacketsBpfMaps,
	)
}

// PacketsBpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPacketsBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type PacketsBpfMaps struct {
	FilterMap        *ebpf.Map `ebpf:"filter_map"`
	GlobalCounters   *ebpf.Map `ebpf:"global_counters"`
	PacketRecord     *ebpf.Map `ebpf:"packet_record"`
	PeerFilterMap    *ebpf.Map `ebpf:"peer_filter_map"`
	SslDataEventMap  *ebpf.Map `ebpf:"ssl_data_event_map"`
	SslFdMap         *ebpf.Map `ebpf:"ssl_fd_map"`
	SslFdPendingMap  *ebpf.Map `ebpf:"ssl_fd_pending_map"`
	SslReadActiveMap *ebpf.Map `ebpf:"ssl_read_active_map"`
}

func (m *PacketsBpfMaps) Close() error {
	return _PacketsBpfClose(
		m.FilterMap,
		m.GlobalCounters,
		m.PacketRecord,
		m.PeerFilterMap,
		m.SslDataEventMap,
		m.SslFdMap,
		m.SslFdPendingMap,
		m.SslReadActiveMap,
	)
}

// PacketsBpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadPacketsBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type PacketsBpfVariables struct {
	EnableFiltering       *ebpf.Variable `ebpf:"enable_filtering"`
	EnableOpensslTracking *ebpf.Variable `ebpf:"enable_openssl_tracking"`
	FilterKey             *ebpf.Variable `ebpf:"filter_key"`
	FilterValue           *ebpf.Variable `ebpf:"filter_value"`
	Sampling              *ebpf.Variable `ebpf:"sampling"`
	SslDataEvent          *ebpf.Variable `ebpf:"ssl_data_event"`
	TraceMessages         *ebpf.Variable `ebpf:"trace_messages"`
	UnusedCounters        *ebpf.Variable `ebpf:"unused_counters"`
}

// PacketsBpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPacketsBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type PacketsBpfPrograms struct {
	NetkitPeerPacketParse    *ebpf.Program `ebpf:"netkit_peer_packet_parse"`
	NetkitPrimaryPacketParse *ebpf.Program `ebpf:"netkit_primary_packet_parse"`
	ProbeEntrySSL_free       *ebpf.Program `ebpf:"probe_entry_SSL_free"`
	ProbeEntrySSL_read       *ebpf.Program `ebpf:"probe_entry_SSL_read"`
	ProbeEntrySSL_setFd      *ebpf.Program `ebpf:"probe_entry_SSL_set_fd"`
	ProbeEntrySSL_write      *ebpf.Program `ebpf:"probe_entry_SSL_write"`
	ProbeRetSSL_read         *ebpf.Program `ebpf:"probe_ret_SSL_read"`
	ProbeRetSSL_setFd        *ebpf.Program `ebpf:"probe_ret_SSL_set_fd"`
	TcEgressPacketParse      *ebpf.Program `ebpf:"tc_egress_packet_parse"`
	TcIngressPacketParse     *ebpf.Program `ebpf:"tc_ingress_packet_parse"`
	TcxEgressPacketParse     *ebpf.Program `ebpf:"tcx_egress_packet_parse"`
	TcxIngressPacketParse    *ebpf.Program `ebpf:"tcx_ingress_packet_parse"`
}

func (p *PacketsBpfPrograms) Close() error {
	return _PacketsBpfClose(
		p.NetkitPeerPacketParse,
		p.NetkitPrimaryPacketParse,
		p.ProbeEntrySSL_free,
		p.ProbeEntrySSL_read,
		p.ProbeEntrySSL_setFd,
		p.ProbeEntrySSL_write,
		p.ProbeRetSSL_read,
		p.ProbeRetSSL_setFd,
		p.TcEgressPacketParse,
		p.TcIngressPacketParse,
		p.TcxEgressPacketParse,
		p.TcxIngressPacketParse,
	)
}

func _PacketsBpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed packetsbpf_powerpc_bpfel.o
var _PacketsBpfBytes []byte
