// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package packets

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type PacketsFilterKeyT struct {
	_         structs.HostLayout
	PrefixLen uint32
	IpData    [16]uint8
}

type PacketsFilterValueT struct {
	_                 structs.HostLayout
	Protocol          uint8
	_                 [1]byte
	DstPortStart      uint16
	DstPortEnd        uint16
	DstPort1          uint16
	DstPort2          uint16
	SrcPortStart      uint16
	SrcPortEnd        uint16
	SrcPort1          uint16
	SrcPort2          uint16
	PortStart         uint16
	PortEnd           uint16
	Port1             uint16
	Port2             uint16
	IcmpType          uint8
	IcmpCode          uint8
	Direction         uint32
	Action            uint32
	TcpFlags          uint32
	FilterDrops       uint8
	_                 [3]byte
	Sample            uint32
	DoPeerCIDR_lookup uint8
	_                 [3]byte
}

type PacketsSslDataEventT struct {
	_           structs.HostLayout
	TimestampNs uint64
	PidTgid     uint64
	DataLen     int32
	SslType     uint8
	Direction   uint8
	TlsSource   uint8
	TupleValid  uint8
	SrcPort     uint16
	DstPort     uint16
	SrcAddr     [16]uint8
	DstAddr     [16]uint8
	SocketFd    int32
	ConnUserPtr uint64
	Data        [16384]int8
}

type PacketsSslFdKeyT struct {
	_      structs.HostLayout
	SslPtr uint64
	Tgid   uint32
	Pad    uint32
}

type PacketsSslReadActiveT struct {
	_           structs.HostLayout
	SslType     uint8
	Pad         [7]uint8
	BufUser     uint64
	ConnUserPtr uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	PacketsMapFilterMap                 = "filter_map"
	PacketsMapGlobalCounters            = "global_counters"
	PacketsMapPacketRecord              = "packet_record"
	PacketsMapPeerFilterMap             = "peer_filter_map"
	PacketsMapSslDataEventMap           = "ssl_data_event_map"
	PacketsMapSslFdMap                  = "ssl_fd_map"
	PacketsMapSslReadActiveMap          = "ssl_read_active_map"
	PacketsProgNetkitPeerPacketParse    = "netkit_peer_packet_parse"
	PacketsProgNetkitPrimaryPacketParse = "netkit_primary_packet_parse"
	PacketsProgProbeEntrySSL_read       = "probe_entry_SSL_read"
	PacketsProgProbeEntrySSL_setFd      = "probe_entry_SSL_set_fd"
	PacketsProgProbeEntrySSL_write      = "probe_entry_SSL_write"
	PacketsProgProbeRetSSL_read         = "probe_ret_SSL_read"
	PacketsProgTcEgressPacketParse      = "tc_egress_packet_parse"
	PacketsProgTcIngressPacketParse     = "tc_ingress_packet_parse"
	PacketsProgTcxEgressPacketParse     = "tcx_egress_packet_parse"
	PacketsProgTcxIngressPacketParse    = "tcx_ingress_packet_parse"
	PacketsVarEnableFiltering           = "enable_filtering"
	PacketsVarEnableOpensslTracking     = "enable_openssl_tracking"
	PacketsVarFilterKey                 = "filter_key"
	PacketsVarFilterValue               = "filter_value"
	PacketsVarSampling                  = "sampling"
	PacketsVarSslDataEvent              = "ssl_data_event"
	PacketsVarTraceMessages             = "trace_messages"
	PacketsVarUnused8                   = "unused8"
	PacketsVarUnused9                   = "unused9"
)

// LoadPackets returns the embedded CollectionSpec for Packets.
func LoadPackets() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PacketsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Packets: %w", err)
	}

	return spec, err
}

// LoadPacketsObjects loads Packets and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PacketsObjects
//	*PacketsPrograms
//	*PacketsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPacketsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPackets()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PacketsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PacketsSpecs struct {
	PacketsProgramSpecs
	PacketsMapSpecs
	PacketsVariableSpecs
}

// PacketsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PacketsProgramSpecs struct {
	NetkitPeerPacketParse    *ebpf.ProgramSpec `ebpf:"netkit_peer_packet_parse"`
	NetkitPrimaryPacketParse *ebpf.ProgramSpec `ebpf:"netkit_primary_packet_parse"`
	ProbeEntrySSL_read       *ebpf.ProgramSpec `ebpf:"probe_entry_SSL_read"`
	ProbeEntrySSL_setFd      *ebpf.ProgramSpec `ebpf:"probe_entry_SSL_set_fd"`
	ProbeEntrySSL_write      *ebpf.ProgramSpec `ebpf:"probe_entry_SSL_write"`
	ProbeRetSSL_read         *ebpf.ProgramSpec `ebpf:"probe_ret_SSL_read"`
	TcEgressPacketParse      *ebpf.ProgramSpec `ebpf:"tc_egress_packet_parse"`
	TcIngressPacketParse     *ebpf.ProgramSpec `ebpf:"tc_ingress_packet_parse"`
	TcxEgressPacketParse     *ebpf.ProgramSpec `ebpf:"tcx_egress_packet_parse"`
	TcxIngressPacketParse    *ebpf.ProgramSpec `ebpf:"tcx_ingress_packet_parse"`
}

// PacketsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PacketsMapSpecs struct {
	FilterMap        *ebpf.MapSpec `ebpf:"filter_map"`
	GlobalCounters   *ebpf.MapSpec `ebpf:"global_counters"`
	PacketRecord     *ebpf.MapSpec `ebpf:"packet_record"`
	PeerFilterMap    *ebpf.MapSpec `ebpf:"peer_filter_map"`
	SslDataEventMap  *ebpf.MapSpec `ebpf:"ssl_data_event_map"`
	SslFdMap         *ebpf.MapSpec `ebpf:"ssl_fd_map"`
	SslReadActiveMap *ebpf.MapSpec `ebpf:"ssl_read_active_map"`
}

// PacketsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PacketsVariableSpecs struct {
	EnableFiltering       *ebpf.VariableSpec `ebpf:"enable_filtering"`
	EnableOpensslTracking *ebpf.VariableSpec `ebpf:"enable_openssl_tracking"`
	FilterKey             *ebpf.VariableSpec `ebpf:"filter_key"`
	FilterValue           *ebpf.VariableSpec `ebpf:"filter_value"`
	Sampling              *ebpf.VariableSpec `ebpf:"sampling"`
	SslDataEvent          *ebpf.VariableSpec `ebpf:"ssl_data_event"`
	TraceMessages         *ebpf.VariableSpec `ebpf:"trace_messages"`
	Unused8               *ebpf.VariableSpec `ebpf:"unused8"`
	Unused9               *ebpf.VariableSpec `ebpf:"unused9"`
}

// PacketsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPacketsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PacketsObjects struct {
	PacketsPrograms
	PacketsMaps
	PacketsVariables
}

func (o *PacketsObjects) Close() error {
	return _PacketsClose(
		&o.PacketsPrograms,
		&o.PacketsMaps,
	)
}

// PacketsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPacketsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PacketsMaps struct {
	FilterMap        *ebpf.Map `ebpf:"filter_map"`
	GlobalCounters   *ebpf.Map `ebpf:"global_counters"`
	PacketRecord     *ebpf.Map `ebpf:"packet_record"`
	PeerFilterMap    *ebpf.Map `ebpf:"peer_filter_map"`
	SslDataEventMap  *ebpf.Map `ebpf:"ssl_data_event_map"`
	SslFdMap         *ebpf.Map `ebpf:"ssl_fd_map"`
	SslReadActiveMap *ebpf.Map `ebpf:"ssl_read_active_map"`
}

func (m *PacketsMaps) Close() error {
	return _PacketsClose(
		m.FilterMap,
		m.GlobalCounters,
		m.PacketRecord,
		m.PeerFilterMap,
		m.SslDataEventMap,
		m.SslFdMap,
		m.SslReadActiveMap,
	)
}

// PacketsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadPacketsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PacketsVariables struct {
	EnableFiltering       *ebpf.Variable `ebpf:"enable_filtering"`
	EnableOpensslTracking *ebpf.Variable `ebpf:"enable_openssl_tracking"`
	FilterKey             *ebpf.Variable `ebpf:"filter_key"`
	FilterValue           *ebpf.Variable `ebpf:"filter_value"`
	Sampling              *ebpf.Variable `ebpf:"sampling"`
	SslDataEvent          *ebpf.Variable `ebpf:"ssl_data_event"`
	TraceMessages         *ebpf.Variable `ebpf:"trace_messages"`
	Unused8               *ebpf.Variable `ebpf:"unused8"`
	Unused9               *ebpf.Variable `ebpf:"unused9"`
}

// PacketsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPacketsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PacketsPrograms struct {
	NetkitPeerPacketParse    *ebpf.Program `ebpf:"netkit_peer_packet_parse"`
	NetkitPrimaryPacketParse *ebpf.Program `ebpf:"netkit_primary_packet_parse"`
	ProbeEntrySSL_read       *ebpf.Program `ebpf:"probe_entry_SSL_read"`
	ProbeEntrySSL_setFd      *ebpf.Program `ebpf:"probe_entry_SSL_set_fd"`
	ProbeEntrySSL_write      *ebpf.Program `ebpf:"probe_entry_SSL_write"`
	ProbeRetSSL_read         *ebpf.Program `ebpf:"probe_ret_SSL_read"`
	TcEgressPacketParse      *ebpf.Program `ebpf:"tc_egress_packet_parse"`
	TcIngressPacketParse     *ebpf.Program `ebpf:"tc_ingress_packet_parse"`
	TcxEgressPacketParse     *ebpf.Program `ebpf:"tcx_egress_packet_parse"`
	TcxIngressPacketParse    *ebpf.Program `ebpf:"tcx_ingress_packet_parse"`
}

func (p *PacketsPrograms) Close() error {
	return _PacketsClose(
		p.NetkitPeerPacketParse,
		p.NetkitPrimaryPacketParse,
		p.ProbeEntrySSL_read,
		p.ProbeEntrySSL_setFd,
		p.ProbeEntrySSL_write,
		p.ProbeRetSSL_read,
		p.TcEgressPacketParse,
		p.TcIngressPacketParse,
		p.TcxEgressPacketParse,
		p.TcxIngressPacketParse,
	)
}

func _PacketsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed packets_arm64_bpfel.o
var _PacketsBytes []byte
