// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: proto/packet.proto

package pbpacket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the Packet
type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pcap          *anypb.Any             `protobuf:"bytes,1,opt,name=pcap,proto3" json:"pcap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_proto_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_proto_packet_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetPcap() *anypb.Any {
	if x != nil {
		return x.Pcap
	}
	return nil
}

// intentionally empty
type CollectorReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorReply) Reset() {
	*x = CollectorReply{}
	mi := &file_proto_packet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorReply) ProtoMessage() {}

func (x *CollectorReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorReply.ProtoReflect.Descriptor instead.
func (*CollectorReply) Descriptor() ([]byte, []int) {
	return file_proto_packet_proto_rawDescGZIP(), []int{1}
}

var File_proto_packet_proto protoreflect.FileDescriptor

const file_proto_packet_proto_rawDesc = "" +
	"\n" +
	"\x12proto/packet.proto\x12\bpbpacket\x1a\x19google/protobuf/any.proto\"2\n" +
	"\x06Packet\x12(\n" +
	"\x04pcap\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x04pcap\"\x10\n" +
	"\x0eCollectorReply2A\n" +
	"\tCollector\x124\n" +
	"\x04Send\x12\x10.pbpacket.Packet\x1a\x18.pbpacket.CollectorReply\"\x00B\x16Z\x14./pb/packet;pbpacketb\x06proto3"

var (
	file_proto_packet_proto_rawDescOnce sync.Once
	file_proto_packet_proto_rawDescData []byte
)

func file_proto_packet_proto_rawDescGZIP() []byte {
	file_proto_packet_proto_rawDescOnce.Do(func() {
		file_proto_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_packet_proto_rawDesc), len(file_proto_packet_proto_rawDesc)))
	})
	return file_proto_packet_proto_rawDescData
}

var file_proto_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_packet_proto_goTypes = []any{
	(*Packet)(nil),         // 0: pbpacket.Packet
	(*CollectorReply)(nil), // 1: pbpacket.CollectorReply
	(*anypb.Any)(nil),      // 2: google.protobuf.Any
}
var file_proto_packet_proto_depIdxs = []int32{
	2, // 0: pbpacket.Packet.pcap:type_name -> google.protobuf.Any
	0, // 1: pbpacket.Collector.Send:input_type -> pbpacket.Packet
	1, // 2: pbpacket.Collector.Send:output_type -> pbpacket.CollectorReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_packet_proto_init() }
func file_proto_packet_proto_init() {
	if File_proto_packet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_packet_proto_rawDesc), len(file_proto_packet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_packet_proto_goTypes,
		DependencyIndexes: file_proto_packet_proto_depIdxs,
		MessageInfos:      file_proto_packet_proto_msgTypes,
	}.Build()
	File_proto_packet_proto = out.File
	file_proto_packet_proto_goTypes = nil
	file_proto_packet_proto_depIdxs = nil
}
