# this file has to be built from the project root directory

FROM golang:1.25 as builder

WORKDIR /app

COPY . .

RUN go build -mod vendor examples/performance/server/packet-counter-collector.go

FROM fedora:42

WORKDIR /
COPY --from=builder /app/packet-counter-collector .

ENTRYPOINT ["/packet-counter-collector"]

