apiVersion: v1
kind: Namespace
metadata:
  name: netobserv-privileged
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netobserv-ebpf-agent
  namespace: netobserv-privileged
  labels:
    k8s-app: netobserv-ebpf-agent
spec:
  selector:
    matchLabels:
      k8s-app: netobserv-ebpf-agent
  template:
    metadata:
      labels:
        k8s-app: netobserv-ebpf-agent
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: netobserv-ebpf-agent
        image: localhost/ebpf-agent:test
        securityContext:
          privileged: true
          runAsUser: 0
        env:
          - name: SAMPLING
            value: "1"
          - name: CACHE_ACTIVE_TIMEOUT
            value: "5s"
          - name: CACHE_MAX_FLOWS
            value: "10000"
          - name: LOG_LEVEL
            value: debug
          - name: TARGET_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: TARGET_PORT
            value: "9999"
          - name: ENABLE_RTT
            value: "true"
          - name: ENABLE_PKT_DROPS
            value: "true"
          - name: ENABLE_DNS_TRACKING
            value: "true"
          - name: ENABLE_OPENSSL_TRACKING
            value: "true"
          - name: OPENSSL_PATH
            value: "/usr/lib/aarch64-linux-gnu/libssl.so.1.1"
          - name: QUIC_TRACKING_MODE
            value: "1"
        volumeMounts:
            - name: bpf-kernel-debug
              mountPath: /sys/kernel/debug
              mountPropagation: Bidirectional
            - name: host-lib
              mountPath: /usr/lib/aarch64-linux-gnu
              readOnly: true
      volumes:
        - name: bpf-kernel-debug
          hostPath:
            path: /sys/kernel/debug
            type: Directory
        - name: host-lib
          hostPath:
            path: /usr/lib/aarch64-linux-gnu
            type: Directory