apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/netobserv/netobserv-ebpf-agent?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "release-1.8"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: netobserv-zstream
    appstudio.openshift.io/component: netobserv-ebpf-agent-zstream
    pipelines.appstudio.openshift.io/type: build
  name: netobserv-ebpf-agent-zstream-on-pull-request
  namespace: ocp-network-observab-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocp-network-observab-tenant/netobserv-ebpf-agent-zstream:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: build-args-file
    value: Dockerfile-args.downstream
  - name: dockerfile
    value: Dockerfile.downstream
  - name: build-platforms
    value:
    - linux/x86_64
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-netobserv-ebpf-agent-zstream
status: {}
