name: Build PR image and upload artifact
on:
  pull_request:
    types: [labeled]

env:
  WF_REGISTRY: quay.io/netobserv
  WF_IMAGE: netobserv-ebpf-agent
  WF_BC_IMAGE: ebpf-bytecode

permissions:
  contents: read

jobs:
  build-pr-image:
    if: ${{ github.event.label.name == 'ok-to-test' }}
    name: Build PR image and upload artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - name: Install make
        run: sudo apt -y install make
      - name: build and save bytecode image
        run: OCI_BUILD_OPTS="--label quay.expires-after=2w" BC_IMAGE=${{ env.WF_REGISTRY }}/${{ env.WF_BC_IMAGE }}:tmp CLEAN_BUILD=1 make tar-bc-image
      - name: build and save image
        run: OCI_BUILD_OPTS="--label quay.expires-after=2w" IMAGE=${{ env.WF_REGISTRY }}/${{ env.WF_IMAGE }}:tmp CLEAN_BUILD=1 make tar-image
      - name: upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: pr
          path: out/
