name: Push PR image to quay.io
on:
  workflow_run:
    workflows: ["Build PR image and upload artifact"]
    types:
      - completed

env:
  WF_REGISTRY_USER: netobserv+github_ci

jobs:
  push-pr-image:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    name: push PR image
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v5
        with:
          name: pr
          run-id: ${{github.event.workflow_run.id }}
          github-token: ${{secrets.GITHUB_TOKEN}}
        # uses: actions/github-script@v3.1.0
        # with:
        #   script: |
        #     var artifacts = await github.actions.listWorkflowRunArtifacts({
        #        owner: context.repo.owner,
        #        repo: context.repo.repo,
        #        run_id: ${{github.event.workflow_run.id }},
        #     });
        #     var matchArtifact = artifacts.data.artifacts.filter(artifact => artifact.name == "pr")[0];
        #     var download = await github.actions.downloadArtifact({
        #        owner: context.repo.owner,
        #        repo: context.repo.repo,
        #        artifact_id: matchArtifact.id,
        #        archive_format: 'zip',
        #     });
        #     var fs = require('fs');
        #     fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
      # - run: unzip artifact
      - name: load images
        run: |
          # docker load --input ./ebpf-agent.tar
          docker load --input ./ebpf-agent-bc.tar
      # - name: docker login to quay.io
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ env.WF_REGISTRY_USER }}
      #     password: ${{ secrets.QUAY_SECRET }}
      #     registry: quay.io
      - name: push images
        run: |
          # DOCKER_BUILDKIT=1 docker push $(cat ./name)
          DOCKER_BUILDKIT=1 docker push $(cat ./bc-name)
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var fs = require('fs');
            var issueNumber = Number(fs.readFileSync('./pr-id'));
            var shortSha = fs.readFileSync('./short-sha');
            # var mainImage = fs.readFileSync('./name');
            var bcImage = fs.readFileSync('./bc-name');
            github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `New images:
            ${mainImage}
            ${bcImage}

            They will expire after two weeks.

            To deploy this build, run from the operator repo, assuming the operator is running:
            \`\`\`bash
            USER=netobserv VERSION=${shortSha} make set-agent-image
            \`\`\`
            `
            })
